---

version: "3.6"

services:
  redis:
    image: redis:5.0.3-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data

volumes:
  redis_data:
